apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: dev
            core-basic: enabled
        values:
          branch: main
    - clusters:
        selector:
          matchLabels:
            env: prod
            core-basic: enabled
        values:
          branch: main
  template:
    metadata:
      name: "{{name}}-argocd"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      sources:
        - repoURL: https://github.com/savagame/GitOps-At-Scale-Multitenancy.git
          targetRevision: main
          ref: valuesRepo
        - repoURL: https://github.com/savagame/GitOps-At-Scale-Multitenancy.git
          targetRevision: "{{values.branch}}"
          path: "./building-a-service-catalog-for-kubernetes/system/argocd"
          helm:
            releaseName: "argocd"
            valueFiles:
              - "values.yaml"
              - "$valuesRepo/building-a-service-catalog-for-kubernetes/cluster/{{name}}/system/argocd/values.yaml"
      destination:
        name: "{{name}}"
        namespace: "argocd"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
