kyverno:
  admissionController:
    replicas: 0
  reportsController:
    replicas: 0
  cleanupController:
    replicas: 0
  backgroundController:
    replicas: 0

  crds:
    install: true
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
      strategy.spinnaker.io/replace: "true"
